[package]
name = "shell"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
beast_crt = { path = "../../libs/beast_crt" }
beast_syscall = { path = "../../libs/beast_syscall" }
beast_font = { path = "../../libs/beast_font" }

[[bin]]
name = "shell"
path = "src/main.rs"
test = false
bench = false