[build]
target = "x86_64-unknown-none"

[target.x86_64-unknown-none]
runner = "scripts/run_qemu.sh"
rustflags = [
    "-C", "link-arg=-Tboot/linker/kernel.ld",
    "-C", "link-arg=-zmax-page-size=0x1000",
    "-C", "link-arg=",
    "-C", "code-model=kernel",
    "-C", "relocation-model=static",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
