# ============================================================================
# Limine Bootloader Configuration for Beast OS
# ============================================================================

timeout: 3

/Beast OS
    protocol: limine
    kernel_path: boot():/boot/beast.kernel
    kernel_cmdline: loglevel=3
    module_path: boot():/boot/initrd.tar
    resolution: 1280x800x32
    serial: yes
